/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import model.InvoiceDetails;
import model.InvoiceTableModel;

/**
 *
 * @author BMT
 */
public class UIFrame extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public UIFrame() {
        controller = new Controller(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceTable = new javax.swing.JTable();
        InvoiceTable.getSelectionModel().addListSelectionListener(controller);
        AddInvoiceBtn = new javax.swing.JButton();
        AddInvoiceBtn.addActionListener(controller);
        DelelteInvoiceBtn = new javax.swing.JButton();
        DelelteInvoiceBtn.addActionListener(controller);
        InvoiceNo = new javax.swing.JLabel();
        InvoiceDate = new javax.swing.JLabel();
        CustomerName = new javax.swing.JLabel();
        TotalInvoice = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        InvoiceDateLabel = new javax.swing.JLabel();
        InvoiceNumberLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemsTable = new javax.swing.JTable();
        AdditemBtn = new javax.swing.JButton();
        AdditemBtn.addActionListener(controller);
        DeleteItemBtn = new javax.swing.JButton();
        DeleteItemBtn.addActionListener(controller);

        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LoadItem = new javax.swing.JMenuItem();
        LoadItem.addActionListener(controller);
        SaveItem = new javax.swing.JMenuItem();
        SaveItem.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        InvoiceTable.setName("Invoices Table"); // NOI18N
        jScrollPane1.setViewportView(InvoiceTable);

        AddInvoiceBtn.setText("Create New Invoice");
        AddInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInvoiceBtnActionPerformed(evt);
            }
        });

        DelelteInvoiceBtn.setText("Delete Invoice");

        InvoiceNo.setText("Invoice Number");
        InvoiceNo.setToolTipText("");

        InvoiceDate.setText("Invoice Date");

        CustomerName.setText("Customer Name");

        TotalInvoice.setText("Invoice Total");

        ItemsTable.setToolTipText("Invoice Table");
        ItemsTable.setName("Invoices Items"); // NOI18N
        jScrollPane2.setViewportView(ItemsTable);

        AdditemBtn.setText("Create Item");
        AdditemBtn.setActionCommand("Create Item");
        AdditemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditemBtnActionPerformed(evt);
            }
        });

        DeleteItemBtn.setText("Delete Item");
        DeleteItemBtn.setToolTipText("");
        DeleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemBtnActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        LoadItem.setText("Load");
        LoadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadItemActionPerformed(evt);
            }
        });
        FileMenu.add(LoadItem);

        SaveItem.setText("Save");
        SaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveItemActionPerformed(evt);
            }
        });
        FileMenu.add(SaveItem);

        jMenuBar1.add(FileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(AddInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(DelelteInvoiceBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AdditemBtn)
                        .addGap(50, 50, 50)
                        .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceDate)
                            .addComponent(InvoiceNo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TotalInvoice)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CustomerName)
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(InvoiceDateLabel)
                                        .addComponent(CustomerNameLabel)
                                        .addComponent(InvoiceNumberLabel))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceNumberLabel)
                            .addComponent(InvoiceNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceDate)
                            .addComponent(InvoiceDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerName)
                            .addComponent(CustomerNameLabel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalInvoice)
                            .addComponent(totalLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DelelteInvoiceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdditemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadItemActionPerformed

    private void SaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveItemActionPerformed

    private void AddInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInvoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddInvoiceBtnActionPerformed

    private void AdditemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdditemBtnActionPerformed

    private void DeleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteItemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInvoiceBtn;
    private javax.swing.JButton AdditemBtn;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JButton DelelteInvoiceBtn;
    private javax.swing.JButton DeleteItemBtn;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel InvoiceDate;
    private javax.swing.JLabel InvoiceDateLabel;
    private javax.swing.JLabel InvoiceNo;
    private javax.swing.JLabel InvoiceNumberLabel;
    private javax.swing.JTable InvoiceTable;
    private javax.swing.JTable ItemsTable;
    private javax.swing.JMenuItem LoadItem;
    private javax.swing.JMenuItem SaveItem;
    private javax.swing.JLabel TotalInvoice;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
private Controller controller;
    public ArrayList<InvoiceDetails> invoices;
    private InvoiceTableModel   invModel;

    public JLabel getTotalLabel() {
        return totalLabel;
    }

    public JLabel getCustomerNameLabel() {
        return CustomerNameLabel;
    }

    public JLabel getInvoiceDateLabel() {
        return InvoiceDateLabel;
    }

    public JLabel getInvoiceNumberLabel() {
        return InvoiceNumberLabel;
    }

    public JLabel getTotalInvoice() {
        return TotalInvoice;
    }

    public Controller getController() {
        return controller;
    }

    public JTable getItemsTable() {
        return ItemsTable;
    }

    public JTable getInvoiceTable() {
        return InvoiceTable;
    }

    public InvoiceTableModel getInvModel() {
        if(invModel ==null){
        invModel=new InvoiceTableModel(getInvoices());
        
        }
        return invModel;
    }

    public void setInvModel(InvoiceTableModel invModel) {
        this.invModel = invModel;
    }

    public ArrayList<InvoiceDetails> getInvoices() {
        if(invoices==null)invoices=new ArrayList<>();
        return invoices;
    }

    public void setInvoices(ArrayList<InvoiceDetails> invoices) {
        this.invoices = invoices;
    }

    public int getNextInvoiceNumber(){
        int number =0;
        for(InvoiceDetails invoiceDetails: invoices){
        
    if(invoiceDetails.getNum()>number)
        number=invoiceDetails.getNum();
    }
            return ++number;

    
}
}